import { cn } from "@/shared/utils";

interface IconProps {
  name: IconName;
  className?: string;
}

/* prettier-ignore */
export const Icon = ({ name, className = "size-4" }: IconProps) => {
  return (
      <svg className={cn("bi size-full shrink-0", className)} viewBox="0 0 16 16" fill="currentColor">
        <use xlinkHref={`/images/icons-sprite.svg#${iconName[name]}`} />
      </svg>
  );
};

export const iconName = {
  add: "plus",
  alert: "exclamation-triangle",
  arrowDown: "arrow-down",
  arrowLeft: "arrow-left",
  arrowRight: "arrow-right",
  arrowUp: "arrow-up",
  at: "at",
  badge: "patch-check",
  bell: "bell",
  briefcase: "briefcase",
  fullscreen: "fullscreen",
  camera: "camera",
  check: "check2",
  checkRound: "check2-circle",
  chevronDown: "chevron-down",
  chevronExpand: "chevron-expand",
  chevronLeft: "chevron-left",
  chevronRight: "chevron-right",
  chevronUp: "chevron-up",
  close: "x",
  collection: "collection",
  color: "droplet",
  conect: "ubuntu",
  company: "buildings",
  database: "database",
  delete: "trash",
  device: "laptop",
  diagram: "diagram-3",
  dot: "dot",
  edit: "pen",
  email: "envelope",
  emailSend: "envelope-at",
  eyeClose: "eye-slash",
  eyeOpen: "eye",
  favorite: "heart",
  favoriteFill: "heart-fill",
  file: "file-earmark",
  filter: "filter",
  flag: "flag",
  flagFill: "flag-fill",
  folder: "folder",
  game: "display",
  google: "google",
  graphUp: "graph-up",
  home: "house",
  i_am: "person_rolodex",
  ia: "stars",
  inbox: "inbox",
  info: "info-lg",
  invite: "envelope-at",
  kanban: "kanban",
  launch: "box-arrow-in-right",
  layers: "layers",
  loading: "hourglass",
  lock: "lock",
  logOut: "box-arrow-left",
  map: "geo-alt",
  moon: "moon-stars",
  more: "three-dots",
  nonProfit: "award",
  options: "three-dots-vertical",
  otp: "123",
  paragraph: "body-text",
  password: "lock",
  people: "people",
  person: "person",
  personCheck: "person-check",
  pieChart: "opencollective",
  play: "play",
  puzzle: "puzzle",
  refresh: "arrow-clockwise",
  reload: "arrow-repeat",
  report: "clipboard",
  save: "floppy",
  screen: "cast",
  search: "search",
  send: "envelope-paper",
  shared: "share",
  shield: "shield-check",
  sidebar: "layout-sidebar-inset",
  soundwave: "soundwave",
  stopwatch: "stopwatch",
  sun: "sun",
  system: "laptop",
  tag: "bookmark",
  target: "crosshair",
  translate: "translate",
  trophy: "trophy",
  unlock: "unlock",
  view: "view-list",
  nut: "nut",
  area: "textarea-resize",
  personal: "person-workspace",
  bezier: "bezier2",
  building: "building-gear",
};

export const appIcons: IconName[] = [
  "company",
  "screen",
  "collection",
  "diagram",
  "graphUp",
  "layers",
  "puzzle",
  "soundwave",
  "view",
  "fullscreen",
  "nut",
  "area",
  "map",
  "conect",
  "game",
  "nonProfit",
  "briefcase",
  "personal",
];
export type IconName = keyof typeof iconName;
